name: "Chapter 12: caching demo"

permissions:
  actions: write
  packages: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      imageRepository:
        required: true
        type: string
        default: 'frontend'
      containerRegistry:
        required: true
        type: string
        default: 'ghcr.io/vriesmarcel'
      dockerfilePath:
        required: true
        type: string
        default: 'frontend/Dockerfile'
      namespace:
        required: true
        type: string
        default: 'globoticket'

jobs:
  build:      
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '8.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.EXTENDED_ACCESSTOKEN }}

      - name: select docker driver
        run: |
          docker buildx create --use --driver=docker-container

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: actions-with-actions/globoticket

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
            context: ${{github.workspace}}
            file: ${{inputs.dockerfilePath}}
            push: true
            tags: ${{inputs.containerRegistry}}/${{inputs.imageRepository}}:${{env.GitVersion_SemVer}}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            labels: ${{steps.meta.outputs.labels}}
     


